# Build stage
FROM node:20-alpine AS builder
RUN apk update
RUN apk add git

RUN npm install -g pm2

WORKDIR /app
RUN git clone https://github.com/SmitErik/quiz_game.git
WORKDIR /app/quiz_game
RUN git checkout devops

WORKDIR /app/quiz_game/server
RUN npm install
RUN npm run build
RUN npm run init

EXPOSE 5000
CMD ["pm2-runtime", "start", "build/index.js"]